SSport/SSport/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sport.urls')),
    path('accounts/', include('accounts.urls')),
]

SSport/sport/urls.py
from django.urls import path
from .views import TrainingListView, TrainingCreateView, ChartView, TrainingDetailView, ExerciseCreateView, SetCreateView, SetExerciseCreateView

app_name = "main"

urlpatterns = [
    path('', TrainingListView.as_view(), name='training-list'),
    path('training/<int:pk>/', TrainingDetailView.as_view(), name="detail"),
    path('training/create/', TrainingCreateView.as_view(), name="training-create"),
    path('<str:user>/chart/', ChartView.as_view(), name="training-chart"),  # Доданий маршрут для графіка
    path('exercise/<int:tr_pk>/create/', ExerciseCreateView.as_view(), name = "exercise"),
    path("training/<int:training_id>/set/create/", SetCreateView.as_view(), name="set-create"),
    path("training/<int:training_id>/set/<int:set_id>/create/", SetExerciseCreateView.as_view(), name="set_exercise-create"),
]

SSport/sport/models.py
from django.db import models
from datetime import date
from accounts.models import CustomUser
from django.utils import timezone

User = CustomUser

class Training(models.Model):
    date = models.DateField(default=date.today)
    started = models.DateField(auto_now_add = True)
    ended = models.DateField(null=True, blank=True)
    note = models.TextField(max_length=200, blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="trainings")

    def __str__(self):
        return f"{self.user}`s training started on {self.date} at {self.started}"

    class Meta:
        verbose_name = "Training"
        verbose_name_plural = "Trainings"


# class ExerciseTitle(models.Model):
#     title = models.CharField(max_length=50, default="")
#     user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="exercisetitles")
#
#     def __str__(self):
#         return f"{self.title}"
#
#     class Meta:
#         verbose_name = "ExerciseTitle"
#         verbose_name_plural = "ExerciseTitles"

class Exercise(models.Model):
    title = models.CharField(max_length=50, default="")
    description = models.TextField(max_length=100, blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="exercises")
    #training = models.ForeignKey(Training, on_delete=models.CASCADE, related_name="exercises")
    def __str__(self):
        return f"{self.title} by {self.user}"

    class Meta:
        verbose_name = "Exercise"
        verbose_name_plural = "Exercises"

class Set(models.Model):
    training = models.ForeignKey(Training, on_delete=models.CASCADE, related_name="sets")
    exercise = models.ForeignKey(Exercise, on_delete=models.CASCADE, related_name="sets")
    note = models.TextField(max_length=200, blank=True, null=True)
    started = models.DateField(auto_now=True)
    ended = models.DateField(blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="sets")
    amount = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f"Set of {self.exercise} started {self.started}"

    class Meta:
        verbose_name = "Set"
        verbose_name_plural = "Sets"


class SetExercise(models.Model):
    set = models.ForeignKey(Set, on_delete=models.CASCADE, related_name="setexercises")
    exercise = models.ForeignKey(Exercise, on_delete=models.CASCADE, related_name="setexercises")
    weight = models.PositiveIntegerField(null=True, blank=True)
    repetition = models.PositiveIntegerField(default=15)
    training = models.ForeignKey(Training, on_delete=models.CASCADE, related_name="setexercisetrainings")
    started = models.DateField(auto_now=True)
    ended = models.DateField(blank=True, null=True)

    def __str__(self):
        return f"{self.set} - {self.weight} - {self.repetition}"

    class Meta:
        verbose_name = "SetExercise"
        verbose_name_plural = "SetExercises"

class Charts(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="charts")
    exercise = models.ForeignKey(Exercise, on_delete=models.CASCADE, related_name="charts")
    start_date = models.DateField(default=timezone.now)
    end_date = models.DateField(default=timezone.now)

SSport/sport/forms.py
from django import forms
from .models import *

class TrainingForm(forms.ModelForm):
    class Meta:
        model = Training
        fields = ['date', "note"]


class ExerciseForm(forms.ModelForm):
    class Meta:
        model = Exercise
        fields = ["title", "description"]


class SetForm(forms.ModelForm):
    class Meta:
        model = Set
        fields = ["exercise", "note"]


class SetExerciseForm(forms.ModelForm):
    class Meta:
        model = SetExercise
        fields = ["weight", "repetition"]

class ChartForm(forms.ModelForm):
    start_date = forms.DateField(required=False, widget=forms.DateInput(attrs={'type': 'date'}))
    end_date = forms.DateField(required=False, widget=forms.DateInput(attrs={'type': 'date'}))

    class Meta:
        model = Charts
        fields = ["exercise", "start_date", "end_date"]
        widgets = {
            "start_date": forms.DateInput(attrs={'type': 'date'}),
            "end_date": forms.DateInput(attrs={'type': 'date'}),
        }

SSport/sport/views.py
import io
import base64
import pandas as pd
import matplotlib

matplotlib.use("Agg")  # Виправлення помилки Matplotlib у Django
import matplotlib.pyplot as plt
from django.shortcuts import render
from django.utils.dateparse import parse_date
from django.views.generic import ListView, CreateView, DetailView, FormView
from django.urls import reverse, reverse_lazy
from .models import *
from .forms import *


# Мапінг назв з GET-запиту на поля у БД
# EXERCISE_MAPPING = {
#     "push_ups": "push_up",
#     "squats": "squat",
#     "presses": "press",
#     "pull_ups": "pull_up",
#     "time_holding": "time_holding",
# }
#
# def training_chart_view(request, user):
#     form = ChartForm(request.GET or None)
#     exercise = Exercise.objects.filter(user = request.user).first()
#     exercise_type = ""
#     start_date = request.GET.get("start_date", "2025-08-01")
#     end_date = request.GET.get("end_date", "2025-08-15")
#     if form.is_valid():
#         exercise_type = form.cleaned_data.get("title", "") # Значення за замовчуванням
#
#     # Конвертація у формат `datetime`
#     start_date = parse_date(start_date)
#     end_date = parse_date(end_date)
#     print(start_date)
#     print(end_date)
#     print(exercise_type)
#
#     # Отримуємо правильне поле з БД
#     exercise_field = EXERCISE_MAPPING.get(exercise_type, exercise)
#
#     # Фільтрація тренувань за датою
#     trainings = Training.objects.filter(started__range=(start_date, end_date)).order_by("started")
#
#     # Формуємо дані для графіка
#     if trainings.exists():
#         data = [{"date": t.date, "value": getattr(t, exercise_field, 0)} for t in trainings]
#     else:
#         data = [{"date": start_date, "value": 0}, {"date": end_date, "value": 0}]
#
#     df = pd.DataFrame(data)
#     df["date"] = pd.to_datetime(df["date"])
#
#     # Побудова графіка
#     plt.figure(figsize=(8, 4))
#     plt.plot(df["date"], df["value"], marker="o", linestyle="-", color="blue", label="Training Progress")
#     plt.xlabel("Дата")
#     plt.ylabel("Кількість повторень")
#     plt.title(f"Прогрес тренувань")
#     plt.legend()
#     plt.grid()
#
#     # Збереження графіка в пам'ять
#     buf = io.BytesIO()
#     plt.savefig(buf, format="png")
#     buf.seek(0)
#     string = base64.b64encode(buf.read()).decode("utf-8")
#     uri = "data:image/png;base64," + string
#     buf.close()
#
#     return render(request, "sport/training_chart.html", {
#         "chart": uri,
#         "start_date": start_date,
#         "end_date": end_date,
#         "exercise_type": exercise_type,
#         "form": form,
#     })

class ChartView(FormView):
    template_name = "sport/training_chart.html"
    form_class = ChartForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        exercise_id = self.request.GET.get("exercise")
        start_date_raw = self.request.GET.get("start_date")
        end_date_raw = self.request.GET.get("end_date")

        if exercise_id and start_date_raw and end_date_raw:
            start_date = parse_date(start_date_raw)
            end_date = parse_date(end_date_raw)
            exercise = Exercise.objects.get(id=exercise_id)

            exercises_qs = SetExercise.objects.filter(
                training__user=self.request.user,
                exercise=exercise,
                started__range=(start_date, end_date)
            )

            if exercises_qs.exists():
                print(exercises_qs)
            else:
                print("None")

            context["exercises_qs"] = exercises_qs

        return context




# Список тренувань
class TrainingListView(ListView):
    model = Training
    template_name = "sport/training.html"
    context_object_name = "trainings"
    ordering = ['date']

# Створення нового тренування
class TrainingCreateView(CreateView):
    model = Training
    template_name = "sport/training_create.html"
    form_class = TrainingForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy("main:training-list")


class TrainingDetailView(DetailView):
    model = Training
    template_name = "sport/training_detail.html"
    context_object_name = "training"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        training = self.get_object()
        context["sets"] = training.sets.all()
        context["set"] = training.sets.first()
        context["exercises"] = SetExercise.objects.filter(training = self.get_object())
        return context


class ExerciseCreateView(CreateView):
    model = Exercise
    template_name = "sport/exercise.html"
    form_class = ExerciseForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        training_id = self.kwargs.get("tr_pk")
        return reverse_lazy("main:detail", kwargs={"pk": training_id})


class SetCreateView(CreateView):
    model = Set
    template_name = "sport/set.html"
    form_class = SetForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        training_id = self.kwargs.get("training_id")
        training = Training.objects.get(id=training_id, user=self.request.user)
        form.instance.training = training
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        training_id = self.kwargs.get("training_id")
        set_id = self.object.id
        return reverse_lazy("main:set_exercise-create", kwargs={"training_id": training_id, "set_id": set_id})


class SetExerciseCreateView(CreateView):
    model = SetExercise
    template_name = "sport/set_exercise.html"
    form_class = SetExerciseForm

    def form_valid(self, form):
        set_id = self.kwargs.get("set_id")
        set = Set.objects.get(id = set_id, user = self.request.user)
        form.instance.set = set
        form.instance.training = set.training
        form.instance.started = set.started
        form.instance.ended = set.ended
        form.instance.exercise = set.exercise
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        set_id = self.kwargs.get("set_id")
        set = Set.objects.get(id=set_id, user=self.request.user)
        context["set"] = set
        return context

    def get_success_url(self):
        training_id = self.object.set.training.id
        return reverse_lazy("main:detail", kwargs={"pk": training_id})

SSport/templates/sport/exercise.html
<form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-success mt-3 w-100">
                <i class="fa-solid fa-floppy-disk"></i> Create
            </button>

SSport/templates/sport/set.html
<form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-success mt-3 w-100">
                <i class="fa-solid fa-floppy-disk"></i> Create
            </button>

SSport/templates/sport/set_exercise.html
{{ set.exercise }}

<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-success mt-3 w-100">
      <i class="fa-solid fa-floppy-disk"></i> Create
  </button>
</form>

SSport/templates/sport/training.html
{% extends "_base.html" %}

{% block title %}Training List | SSport{% endblock %}

{% block content %}
<div class="text-center mb-4">
    <h1 class="fw-bold text-primary"><i class="fa-solid fa-list-check"></i> Training Sessions</h1>
    <p class="text-muted">Track your progress and stay motivated!</p>
</div>

<div class="row">
    {% for training in trainings %}
    <div class="col-md-6 col-lg-4">
        <div class="card training-card shadow-sm mb-4">
            <div class="card-body">
                <h5 class="card-title text-success"><i class="fa-solid fa-calendar-check"></i> {{ training.date }}</h5>
                <p class="card-text">
                    {% if training.note %}
                    <strong> {{ training.note }} </strong>
                    {% endif %}
                </p>
                <a href="{% url 'main:detail' training.id %}" class="btn btn-success me-2">Переглянути</a>
            </div>
        </div>
    </div>
    {% empty %}
    <div class="col-12">
        <div class="alert alert-warning text-center">
            <i class="fa-solid fa-triangle-exclamation"></i> No training sessions available.
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

SSport/templates/sport/training_chart.html
<form method="get">
    {{ form.exercise }}
    {{ form.start_date }}
    {{ form.end_date }}
    <button type="submit">Фильтровать</button>
</form>

SSport/templates/sport/training_create.html
{% extends "_base.html" %}

{% block title %}Create Training | SSport{% endblock %}

{% block content %}
<div class="container d-flex justify-content-center mt-5">
    <div class="form-container">
        <h2 class="text-center text-primary mb-4">
            <i class="fa-solid fa-plus-circle"></i> Create Training Session
        </h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-success mt-3 w-100">
                <i class="fa-solid fa-floppy-disk"></i> Save
            </button>
        </form>
    </div>
</div>
{% endblock %}

{% block extra_styles %}
<style>
    .form-container {
        max-width: 500px;
        background: white;
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);
    }
</style>
{% endblock %}

SSport/templates/sport/training_detail.html
{{ set.exercise }}
{% for set1 in sets %}
Сет: {{ set1 }} </br>
{% for exercise in exercises%}
{% if exercise.set == set1 %}
Вправа: {{ exercise }}
{% endif %}



<a href="{% url 'main:set_exercise-create' training_id=set.training.pk set_id=set.pk %}">Add exercise</a>
{% endfor %}
{% endfor %}
<br/>
<a href="{% url 'main:set-create' training.pk %}">Почати сет</a>
<a href="{% url 'main:exercise' training.pk %}">Додати тренування</a>